---
- set_fact:
    pcs_upgrade_hosts: "{{ item | reject('none') |  join(',') + ',' + pcs_upgrade_hosts }}"
  when: pcs_present

- name: create compute pre upgrade script for {{ item }}
  when:
    - compute_present | bool
    - workload_launch | bool
  vars:
    node_name: "{{ item | reject('none') | join(',') }}"
  template:
    src: "node_upgrade_pre.sh.j2"
    dest: "{{ node_name }}_upgrade_pre.sh"
    mode: 0775
    force: true

- name: create overcloud system upgrade script for {{ item }}
  vars:
    hosts: "{{ item | reject('none') | join(',') }}"
  template:
    src: "fast-forward-upgrade/overcloud_system_upgrade.sh.j2"
    dest: "{{ overcloud_system_upgrade_script_base }}-{{ hosts }}.sh"
    mode: 0775
    force: true

- name: create overcloud upgrade script for {{ item }}
  vars:
    hosts: "{{ pcs_upgrade_hosts | regex_replace(',$', '')
            if pcs_present else item | reject('none') | join(',') }}"
    transfer_data: >
      {{ inventory_hostmap.mysql | intersect (item) | length > 0 }}
    stop_services: >
      {{ inventory_hostmap.pacemaker | intersect (item) | length > 0 }}
  template:
    src: "fast-forward-upgrade/overcloud_upgrade_run.sh.j2"
    dest: "{{ overcloud_upgrade_run_script_base }}-{{ hosts }}.sh"
    mode: 0775
    force: true
