---
# tasks file for tripleo-upgrade

- block:
    - name: prepare workload scripts
      include: common/create_workload.yml

    - name: launch workload
      shell: |
        set -o pipefail
        bash {{ workload_launch_script }} 2>&1 {{ timestamper_cmd }} > workload_launch.log
      args:
        chdir: "{{ working_dir }}"

  when: workload_launch

- include: upgrade/main.yml
  when: >
      upgrade_noop|bool or
      undercloud_upgrade|bool or
      undercloud_os_upgrade|bool or
      overcloud_upgrade|bool

- include: update/main.yml
  when: >
      update_noop|bool or
      undercloud_update|bool or
      overcloud_update|bool

- include: fast-forward-upgrade/main.yml
  when: >
      ffu_noop|bool or
      ffu_undercloud_upgrade|bool or
      ffu_overcloud_upgrade|bool
