---
- name: Ensure we skip Rhel Enforcement
  include_tasks: ../common/skip_rhel_enforcement.yaml
  when: not ( enforce_rhel|bool )

- name: create a comptatible deployment scripts from oooq
  include_tasks: ../upgrade/use_oooq.yaml
  args:
    apply:
      tags:
        - use_oooq
  tags: use_oooq
  when: use_oooq|bool

- name: Convert CLI options to parameters
  import_tasks: ../common/convert_cli_opts_params.yaml

- name: get auxiliary facts for major upgrades
  import_tasks: ../common/auxilary-facts.yaml

# TODO: Not comptatible with oooq
- name: Build extra templates based on new options.
  import_tasks: ../common/build_extra_template.yaml
  when: not use_oooq|bool

- name: create undercloud update script
  template:
    src: "undercloud_upgrade.sh.j2"
    dest: "{{ undercloud_update_script }}"
    mode: 0775
    force: true

- name: create scripts with workarounds
  template:
    src: "workarounds.sh.j2"
    dest: "{{ working_dir }}/{{ item }}.sh"
    mode: 0755
    force: true
  loop:
    - 'pre_overcloud_update_prepare_workarounds'
    - 'post_overcloud_update_prepare_workarounds'
    - 'pre_overcloud_update_run_workarounds'
    - 'post_overcloud_update_run_workarounds'
  when: updates_workarounds|bool

- name: include l3 agent tasks
  import_tasks: ../common/create_l3_agent_connectivity_check_script.yml

- name: generate roles list from inventory file
  import_tasks: ../common/load_roles_from_inventory.yaml

- name: create overcloud update prepare script
  vars:
    old_img: "{{ working_dir }}/{{ container_registry_file }}"
  template:
    src: "overcloud_update_prepare.sh.j2"
    dest: "{{ overcloud_update_prepare_script }}"
    mode: 0775
    force: true

- name: create overcloud_prepare_containers.sh script
  template:
    src: overcloud_prepare_containers.sh.j2
    dest: "{{ working_dir }}/overcloud_prepare_containers.sh"
    mode: 0755
    force: true

- name: create overcloud update script
  template:
    src: "overcloud_update_run.sh.j2"
    dest: "{{ overcloud_update_run_script_base }}-{{ item }}.sh"
    mode: 0775
    force: true
  loop: "{{ oc_roles|default(['all']) }}"

- name: create online data migration script
  template:
    src: "overcloud_online_data_migration.sh.j2"
    dest: "{{ working_dir }}/overcloud_online_data_migration.sh"
    mode: 0755
    force: true

- name: create docker container/images validate scripts
  template:
    src: "validate_docker_images_versions.sh.j2"
    dest: "{{ overcloud_validate_images_script }}"
    mode: 0755
    force: true

- name: create ceph update script
  template:
    src: "ceph-update-run.sh.j2"
    dest: "{{ working_dir }}/ceph-update-run.sh"
    mode: 0755
    force: true

- name: Create L3-agent failover scripts
  import_tasks: ../common/create_l3_agent_failover_check_script.yml

- name: create nova actions check script
  import_tasks: ../common/create_nova_actions_check_script.yml

- name: import create HTTP test scripts
  import_tasks: ../common/create_http_test_scripts.yml
