---
- name: rename FluentdClient to Fluentd
  # https://bugzilla.redhat.com/show_bug.cgi?id=1540546
  replace:
    path: "{{ roles_data }}"
    regexp: '(\s+)- OS::TripleO::Services::FluentdClient$'
    replace: '\1- OS::TripleO::Services::Fluentd'

- name: remove ManilaBackendGeneric resource
  # https://bugzilla.redhat.com/show_bug.cgi?id=1541382
  replace:
    path: "{{ roles_data }}"
    regexp: '(\s+)- OS::TripleO::Services::ManilaBackendGeneric$'
    replace: ''

- name: check CephMgr service present
  shell: |
    grep -q 'OS::TripleO::Services::CephMgr' {{ roles_data }}
  register: ceph_mgr_found
  failed_when: false

- name: add CephMgr service
  lineinfile:
    path: "{{ roles_data }}"
    backrefs: true
    regexp: '(\s+)(- OS::TripleO::Services::CephMon$)'
    line: '\1- OS::TripleO::Services::CephMgr\n\1\2'
    insertbefore: '- OS::TripleO::Services::CephMon'
  when: ceph_mgr_found.rc == 1
