---
- name: Running post upgrade scripts for {{ node_name | splitext | first }}
  shell: "set -o pipefail && {{working_dir}}/{{ node_name | splitext | first }}_post/{{ item }}.sh"
  with_items:
    - 'haproxy'
    - 'haproxy_backend'
    - 'rabbitmq'
    - 'redis'
