---
- name: run major upgrade converge step
  shell: "bash {{ overcloud_upgrade_converge_script }} 2>&1 {{ timestamper_cmd }} > \
    {{ working_dir }}/overcloud_upgrade_converge.log"
  register: overcloud_converge_upgrade
  ignore_errors: yes

- block:
    - name: print stack failures
      shell: |
        set -o pipefail
        source {{ undercloud_rc }}
        openstack stack failures list --long {{ overcloud_stack_name }} 2>&1 {{ timestamper_cmd }} | \
          tee {{ working_dir}}/overcloud_composable_failed_upgrade_converge.log

    - name: was the overcloud upgrade converge successful.
      fail: msg="Overcloud upgrade converge step failed... :("
  when: overcloud_converge_upgrade.rc != 0
