---
- name: Create FIP HTTP check scripts
  template:
    src: "{{ item }}"
    dest: "{{working_dir}}/{{ item.split('.') | first }}.sh"
    mode: 0775
  with_items:
      - 'fip_http_check_start.sh.j2'
      - 'fip_http_check_stop.sh.j2'
